# Generated by Django 4.2.5 on 2023-11-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/company-logo/'),
        ),
    ]
