# Generated by Django 4.2.5 on 2023-11-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_logo',
            field=models.ImageField(blank=True, default='org_logo/org-logo.png', null=True, upload_to='images/company-logo/'),
        ),
    ]
